### ISSUE TITLE
Keyboard Mode Not Working

### ISSUE THREAD

**Issue by embraceentropy** [falcon71/kln90b#13]
After clicking the CRSR spot it turns to KYBD, but keyboard inputs are not showing in the selected field where the cursor is blinking. Is there another step needed to use this functionality?

**Comment by falcon71** [comment]
Once it displays KYBD, no further steps are required. You should be able to type right away. Some fields can't be typed directly, like numbers that have more than one decimal or fields that show symbols. 
Please try it  with the ICAO code in the FPL page or on the APT page, it should definitely work there.

**Comment by falcon71** [comment]
@embraceentropy Do you still have problems with keyboard mode? If not please let me know and I will close this issue.

**Comment by embraceentropy** [comment]
@falcon71 Apologies for not closing the loop! The keyboard function is working on the FPL & DTO page. I was trying it on the VNAV page when trying to specify the waypoint. If this feature is not intended for use on the VNAV page then it should be closed.

**Comment by falcon71** [comment]
@embraceentropy I just tried changing the VNAV waypoint with the keyboard and it works for me. The only issue is that ENT does not work for confirmation, because the CRSR gets disabled in the confirm dialogue.
Can you please try again, maybe with the newest beta?:
https://github.com/falcon71/kln90b/releases/tag/v1.2-b2

**Comment by falcon71** [comment]
I'm closing this issue. Please let me know if you still have problems. You can also join our Discord if you need help:
https://discord.gg/ZdQ6htedtT

**Comment by embraceentropy** [comment]
@falcon71 sorry about that. I haven't had a chance to try it with the beta. thank you for your support!
