### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by lrargerich** [falcon71/kln90b#2]
Hi, I tried a very simple replacement for the GPS in one of the planes I have.

I  replaced this:
[VCockpit05]
size_mm				= 320,234
pixel_size			= 320,234
texture				= $AS530
htmlgauge00=NavSystems/GPS/AS530/AS530.html, 0, 0, 320, 234

With this:
[Vcockpit05]
size_mm = 860,388
pixel_size = 860,388
texture=$KLN90B_Screen
htmlgauge00=NavSystems/GPS/KLN90B/KLN90B.html, 0, 0, 860,388

The result is that I have a white page/screen in the GPS, maybe I'm missing something but I thought changing the panel.cfg and putting the GPS in the Community Folder would be enough.

Any help would be appreciated!
Luis.

**Comment by falcon71** [comment]
Your texture probably doesn't exist. For testing you can use `texture = $AS530`. Please keep in mind, that the KLN cannot be used as a simple replacement for the GNS 530, as it uses entirely different events that the KLN does not listen to.

**Comment by lrargerich** [comment]
My plan is to program the H: events with Spad Next and map those to a StreamDeck plus so I think I only need the KLN screen to display properly and I can handle the GPS using my hardware. Right?

**Comment by falcon71** [comment]
Yes, you are right. I did actually initially develop the KLN using the GNS 430 bezel. The H events are all you need to control the device:
https://github.com/falcon71/kln90b/blob/main/kln90b/HEvents.ts
It's just not gonna be pretty and the aspect ratio will be off. Have fun and please let me know if your problem is resolved so I can close this issue.

**Comment by lrargerich** [comment]
This is how panel.cfg looks like:

[VCockpit04]

size_mm = 860,388
pixel_size = 860,388
texture=$AS530
htmlgauge00=NavSystems/GPS/KLN90B/KLN90B.html, 0, 0, 860,388

But I'm still getting a totally white screen on the GPS.

**Comment by lrargerich** [comment]
Made progress, now I have a black screen.
I tried sending H:KLN90B_Power_Toggle
but is not working, the screen is totally black.

**Comment by falcon71** [comment]
Ok, a black screen is at least some progress. Please try to start on the runway with engines running. The KLN 90B should start ready to be used with its screen on.
Are you familiar with the Coherent GT debugger from the MSFS SDK? With that tool you can see if the instrument has loaded correctly.

**Comment by lrargerich** [comment]
Starting with engines running does make the KLN work! What should I do to make it work from cold & dark?

**Comment by falcon71** [comment]
Very good! `H:KLN90B_Power_Toggle` should be the only thing needed to turn it on (assuming you have not defined the `ElectricitySimVar` in the panel.xml). Have you waited a few seconds after sending this event for the screen to warm up? It takes a little while for the screen to show an image.
You may also want to try if the H Events are actually working for you. Try sending `H:KLN90B_RightLargeKnob_Right` or `H:KLN90B_ENT_Push` to see if it does anything when the display is on.

**Comment by lrargerich** [comment]
Yes, the H: events are working, I sent a knob left event and changed the left page. I will try again to see if the GPS screen can start from cold & dark. 
I've also noticed that I couldn't make the screen brighter in the sim with the corresponding event but it did work in the popup (if I pop out the panel).
I will be doing some tests and come back if I have some problem, I think you can close this ticket now as it was about a white screen and that is solved using the right texture.

**Comment by lrargerich** [comment]
Just in case you can help me:
I'm not being able to change the brightness of the KLN screen. The events do work but the LVAR for brightness only goes up to 0.01 and it is very very dim in the sim. Also the popped out version is on the other side too bright and I can't dim it.

**Comment by falcon71** [comment]
This is quite weird. The H events should be all you need to control everything. Do you intend to buy the Dukes? It might be easier for you to program your StreamDeck with a fully supported aircraft and make sure it works with that one, before venturing to a hacked default aircraft.

**Comment by falcon71** [comment]
Since the white screen has been resolved, I'm closing this issue. The Dukes are now available and the A2A Comanche will follow soon. Please try, if you can get your StreamDeck to work in one of those official planes and file a new issue if you still have problems.
