### ISSUE TITLE
Unrecoverable error when trying to cancel D-TO

### ISSUE THREAD

**Issue by walterbeech** [falcon71/kln90b#30]
1. Call the NRST page (MSG ENT).
2. Press D-TO.
3. Press CLR.

![image](https://github.com/falcon71/kln90b/assets/70887419/7c94d120-b73f-44fd-b483-1eb78d927756)

**Comment by walterbeech** [comment]
![image](https://github.com/falcon71/kln90b/assets/70887419/2a3270c7-01e3-4240-b356-4103669d966c)

**Comment by falcon71** [comment]
Hello @walterbeech. Thanks for your report. This error was already noted in #12 and was fixed in version 1.2. Please update to the latest release:
https://github.com/falcon71/kln90b/releases/latest
