### ISSUE TITLE
Restart in OBS mode

### ISSUE THREAD

**Issue by walterbeech** [falcon71/kln90b#37]
Consider the following scenario (tested on A2A Comanche):

1. The unit is in the OBS mode.
2. The avionics bus power is removed.
3. The avionics bus power is restored.

At this stage, the unit detects it is in OBS mode and requests a CRS button press. However, pressing the CRS button doesn't have any effect — the only way to complete the unit start up is to deselect OBS on the panel.

**Comment by falcon71** [comment]
Thank you for your report. I tried your steps, but I was not able to reproduce the issue. When I restart the unit in OBS mode, I do get the warning message. As soon as I press the CRS button, it switches to LEG mode and the warning message disappears.
Can you please check which version you are using? You can see it on the STA 3 page at line 4. 
If you can reproduce the issue, then I would love to see screenshots or a video. Maybe there are a few more steps required, that I have overlooked?

**Comment by walterbeech** [comment]
No, all steps are there. However, reproducing it for a video (see below), I thought that it might have been me who misunderstood the unit operation. I was referring to the CRS button on the unit bezel (which does nothing when pressed as can be seen in the video), but perhaps the message specifies the panel mounted button?

I'm currently using 1.4.1.

Here is the video:
https://youtu.be/xU9k_30CPfQ

**Comment by falcon71** [comment]
Ah, thank you very much for the video, now it is clear. You are pressing the CRSR (cursor) button, but the message asks for the CRS (course) button on the remote annunciator. 
The reason why the message exists is that the CRS button is not a toggle button, but a two position switch. The KLN cannot change the state of the switch its own, so the pilot must do it.
I'm certain, the behavior from this simulation is correct and true to the real unit.

**Comment by walterbeech** [comment]
I see. Thanks for the clarification.
