### ISSUE TITLE
ERR: NULL IS NOT AN OBJ

### ISSUE THREAD

**Issue by lrargerich** [falcon71/kln90b#4]
I got the MSG flashing on the KLN90 with this error message.
It happened in a second leg of a flight after landing, shutting down and then starting the plane again without ever leaving to the MSFS menu, so maybe related to this. 

The error says:

ECT EVALUATING EICAO
1: 808311 1: 808292
1: 908074 1: 807076
1: 340025

**Comment by falcon71** [comment]
Thank you, this error will be fixed in the next version.
