### ISSUE TITLE
1.5-beta2 stuck in Self Test

### ISSUE THREAD

**Issue by aurel42** [falcon71/kln90b#42]
Hey falcon, thanks for recreating this neat device for MSFS! I really appreciate it, it's one of my favorite add-ons.

Using 1.5-beta2 in the Blacksquare Duke, the unit never completes the self test. It's stuck at the self test screen and generally unresponsive.
Reverting to 1.4.3 resolved the issue.

Please let me know if I can provide more information.

**Comment by falcon71** [comment]
Thanks for the report, I noticed it myself a few minutes ago. The problem occurs if you have no user waypoints. I will publish a fix very soon.

**Comment by falcon71** [comment]
@aurel42 Fixed in beta 3: 
https://github.com/falcon71/kln90b/releases/tag/v1.5-b3
Thanks again!
