### ISSUE TITLE
Add all RNAV approaches

### ISSUE THREAD

**Issue by falcon71** [falcon71/kln90b#6]
The KLN currently only displays approaches encoded as "GPS". This limits it's functionality in the sim quite a lot. Instead all RNAV approaches should be available, except those that make use of RF legs.

**Comment by mattnischan** [comment]
One important note for implementing support for this: the best service level the KLN can provide for any procedure labeled GPS, RNAV, or RNP would be the LNAV service level. The KLN does not have a SBAS receiver, which eliminates the ability to do LP, LPV and SBAS coupled LNAV/VNAV service levels. It also is not certified for baro-VNAV, so cannot do LNAV/VNAV in baro-VNAV.

For the framework, that means you would need to ensure that your VNAV manager publishers `GlidePathServiceLevel.None` for all of those approaches.

**Comment by mattnischan** [comment]
Also, just a note on 117f548, there are quite many approaches labeled "RNP" worldwide which are not RNP AR but just regular RNAV minima approaches, as the new naming ICAO conventions dictate (the US is slow on the uptake). Thus a lot of valid approaches will be filtered out, especially in Europe (and especially with Navigraph installed).

The filter then necessary is:
- Does the approach have LNAV, LNAV/VNAV, LP, or LPV (RNavTypeFlags), if so, then it is what the unit would consider an RNAV approach even if the name starts with RNP
- If not the above, does the procedure _not_ have any assigned runways? If so then it might be either a RNP AR or RNAV circling approach. The best filter here would be to check for any legs in the procedure with RF type, and filter out those approaches.

**Comment by falcon71** [comment]
Thanks @mattnischan! You are right, it makes sense to filter based on rnavTypeFlags, good idea. The KLN does not have any vertical guidance, so it should only allow approaches that are allowed for LNAV only.

I still have trouble identifying RNP approaches. For example take a look the the RNP approaches at EDDF. Those are marked LNAV only, but RNP. Is there any way to recognize, that those are RNP approaches instead of simple GPS approaches?

**Comment by mattnischan** [comment]
> I still have trouble identifying RNP approaches. For example take a look the the RNP approaches at EDDF. Those are marked LNAV only, but RNP.

@falcon71 This is actually a good example. The RNP approaches at EDDF are ones that previously would have been named "RNAV" and are now named "RNP" under the new ICAO naming conventions. So, they're actually regular RNAV-style approaches, what I've been terming _approaches with RNAV minima_ when I talk to folks, to try and disambiguate from approaches with only RNP minima. If the approach has only RNP minima, it won't have any RNAV minima, so no RNavTypeFlags will be set in the data; that's a good indicator. Approaches without RNAV minima wouldn't be flyable by the unit.

I think what you have now looks good to me! Although I think in your latest commit you accidentally dropped some of the other non-precision approaches from being valid (it looks like they all fall through to the default false case now).

**Comment by falcon71** [comment]
@mattnischan Thank you for noticing. You are right, I just dropped all non-precision approaches...

Very interesting, I did not know about those new naming conventions. The problem is still, that the approaches in EDDF require RNP-1. The KLN is not P-RNAV certified, only B-RNAV. This would actually significantly reduce the number of available SIDs, STARs and approaches. As far as I can tell, that data is not available in the sim.
Still, I think the current compromise is good enough for the sim, so pilots can still enjoy some approaches, even if the real KLN would be pretty much useless these days.

**Comment by mattnischan** [comment]
> The problem is still, that the approaches in EDDF require RNP-1.

Ah yep, you're right, I did not catch that (was overfocused on the minima). Yeah, unfortunately, that data is not currently available in the sim, though we would like to get that in someday.

> Still, I think the current compromise is good enough for the sim, so pilots can still enjoy some approaches, even if the real KLN would be pretty much useless these days.

Agreed!
